name: education_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  animations:
  video_player:
  image_picker:
  json_annotation:
  shared_preferences:
  path:
  path_provider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_ui_auth:
  firebase_ui_firestore:
  firebase_ui_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/
